/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import Rocket from '../components/rocket'
import styles from '../styles/Home.module.css'
import Space from '../components/space'
import Navbar from '../components/navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Space Age</title>
        <meta name="description" content="Generated by Next.js" />
        <link rel="icon" href="spaceage.png" />
      </Head>
      <Space />
      <Navbar />
      
      {/* Main Content */}
      <main className={styles.main}>
        <div className={styles.mainLeft}>
          <h1 className={styles.title}>Space Age</h1>
          <p className={styles.description}>Web3 is like a spacecraft, we are the astronauts.</p>
        </div>
        <div className={styles.mainRight}>
        <video autoPlay muted loop className={styles.ufoVideo}>         
            <source src="/ufo.mp4" type="video/mp4"/>       
        </video>
        </div>  
      </main>
    </div>
  )
}
